// <auto-generated />
using System.Globalization;

namespace NetEscapades.Configuration.Yaml
{
    internal static class Resources
    {
        /// <summary>
        /// A duplicate key '{0}' was found.
        /// </summary>
        internal static string FormatError_KeyIsDuplicated(object p0)
        {
            return string.Format(CultureInfo.CurrentCulture, "A duplicate key '{0}' was found.", p0);
        }
    }
}